// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT time_hour

lv_obj_t *ui_time_hour_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_time_hour;
cui_time_hour = lv_label_create(comp_parent);
lv_obj_set_width( cui_time_hour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_time_hour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_time_hour, -1 );
lv_obj_set_y( cui_time_hour, -133 );
lv_obj_set_align( cui_time_hour, LV_ALIGN_CENTER );
lv_label_set_text(cui_time_hour,"10:49");
lv_obj_set_style_text_color(cui_time_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_time_hour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_time_hour, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TIME_HOUR_NUM);
children[UI_COMP_TIME_HOUR_TIME_HOUR] = cui_time_hour;
lv_obj_add_event_cb(cui_time_hour, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_time_hour, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_time_hour_create_hook(cui_time_hour);
return cui_time_hour; 
}

