// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_weathericon;
lv_obj_t *uic_Tempmax;
lv_obj_t *uic_Tempmin;
lv_obj_t *uic_Temp;
lv_obj_t *uic_timesecond;
lv_obj_t *uic_timeminute;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_timeminute = NULL;lv_obj_t *ui_timehour1 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_timesecond = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_Temp = NULL;lv_obj_t *ui_Tempmin = NULL;lv_obj_t *ui_Tempmax = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Panel5 = NULL;lv_obj_t *ui_date = NULL;lv_obj_t *ui_Panel6 = NULL;lv_obj_t *ui_weathericon = NULL;lv_obj_t *ui_Panel7 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Image1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 76);
lv_obj_set_height( ui_Panel1, 107);
lv_obj_set_x( ui_Panel1, -42 );
lv_obj_set_y( ui_Panel1, -101 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeminute = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_timeminute, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeminute, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeminute, -44 );
lv_obj_set_y( ui_timeminute, -75 );
lv_obj_set_align( ui_timeminute, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeminute,"49");
lv_obj_set_style_text_color(ui_timeminute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeminute, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timeminute, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_timeminute, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_timeminute, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_timeminute, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_timeminute, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timehour1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_timehour1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timehour1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timehour1, -43 );
lv_obj_set_y( ui_timehour1, -127 );
lv_obj_set_align( ui_timehour1, LV_ALIGN_CENTER );
lv_label_set_text(ui_timehour1,"10:");
lv_obj_set_style_text_color(ui_timehour1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timehour1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timehour1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_timehour1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_timehour1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_timehour1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_timehour1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 76);
lv_obj_set_height( ui_Panel2, 58);
lv_obj_set_x( ui_Panel2, 41 );
lv_obj_set_y( ui_Panel2, -124 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timesecond = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_timesecond, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timesecond, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timesecond, 41 );
lv_obj_set_y( ui_timesecond, -124 );
lv_obj_set_align( ui_timesecond, LV_ALIGN_CENTER );
lv_label_set_text(ui_timesecond,"38");
lv_obj_set_style_text_color(ui_timesecond, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timesecond, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timesecond, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 158);
lv_obj_set_height( ui_Panel3, 45);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, 33 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel3, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel4, 76);
lv_obj_set_height( ui_Panel4, 48);
lv_obj_set_x( ui_Panel4, -41 );
lv_obj_set_y( ui_Panel4, -17 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel4, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temp, -41 );
lv_obj_set_y( ui_Temp, -16 );
lv_obj_set_align( ui_Temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temp,"61C");
lv_obj_set_style_text_color(ui_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temp, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Tempmin = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Tempmin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Tempmin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Tempmin, -52 );
lv_obj_set_y( ui_Tempmin, 32 );
lv_obj_set_align( ui_Tempmin, LV_ALIGN_CENTER );
lv_label_set_text(ui_Tempmin,"40C");
lv_obj_set_style_text_color(ui_Tempmin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Tempmin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Tempmin, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Tempmax = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Tempmax, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Tempmax, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Tempmax, 52 );
lv_obj_set_y( ui_Tempmax, 33 );
lv_obj_set_align( ui_Tempmax, LV_ALIGN_CENTER );
lv_label_set_text(ui_Tempmax,"70C");
lv_obj_set_style_text_color(ui_Tempmax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Tempmax, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Tempmax, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 0 );
lv_obj_set_y( ui_Label7, 33 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"---------");

ui_Panel5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel5, 76);
lv_obj_set_height( ui_Panel5, 42);
lv_obj_set_x( ui_Panel5, 41 );
lv_obj_set_y( ui_Panel5, -68 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel5, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_date, 40 );
lv_obj_set_y( ui_date, -68 );
lv_obj_set_align( ui_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_date,"Sun 29");
lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel6, 76);
lv_obj_set_height( ui_Panel6, 47);
lv_obj_set_x( ui_Panel6, 41 );
lv_obj_set_y( ui_Panel6, -18 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel6, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel6, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weathericon = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_weathericon);
lv_obj_set_width( ui_weathericon, 71);
lv_obj_set_height( ui_weathericon, 41);
lv_obj_set_x( ui_weathericon, 41 );
lv_obj_set_y( ui_weathericon, -18 );
lv_obj_set_align( ui_weathericon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_weathericon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel7 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel7, 158);
lv_obj_set_height( ui_Panel7, 91);
lv_obj_set_x( ui_Panel7, 0 );
lv_obj_set_y( ui_Panel7, 107 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel7, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel7, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -1 );
lv_obj_set_y( ui_Label1, 106 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"- Meeting with Alex @10pm\n\n- Finish debuging stasis\n\n- Review projects\n\n- Submit stasis project");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_cloud_icon_128x128_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 41 );
lv_obj_set_y( ui_Image1, -12 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,120);

uic_timeminute = ui_timeminute;
uic_timesecond = ui_timesecond;
uic_Temp = ui_Temp;
uic_Tempmin = ui_Tempmin;
uic_Tempmax = ui_Tempmax;
uic_weathericon = ui_weathericon;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Panel1= NULL;
uic_timeminute= NULL;
ui_timeminute= NULL;
ui_timehour1= NULL;
ui_Panel2= NULL;
uic_timesecond= NULL;
ui_timesecond= NULL;
ui_Panel3= NULL;
ui_Panel4= NULL;
uic_Temp= NULL;
ui_Temp= NULL;
uic_Tempmin= NULL;
ui_Tempmin= NULL;
uic_Tempmax= NULL;
ui_Tempmax= NULL;
ui_Label7= NULL;
ui_Panel5= NULL;
ui_date= NULL;
ui_Panel6= NULL;
uic_weathericon= NULL;
ui_weathericon= NULL;
ui_Panel7= NULL;
ui_Label1= NULL;
ui_Image1= NULL;

}
