// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_timeminute;
extern lv_obj_t *ui_timehour1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_timesecond;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Temp;
extern lv_obj_t *ui_Tempmin;
extern lv_obj_t *ui_Tempmax;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_date;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_weathericon;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_timeminute;
extern lv_obj_t *uic_timesecond;
extern lv_obj_t *uic_Temp;
extern lv_obj_t *uic_Tempmin;
extern lv_obj_t *uic_Tempmax;
extern lv_obj_t *uic_weathericon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

